theme: jekyll-theme-cayman
title: Şeffaflık Platformu
description: Enerji Piyasaları İşletme A.Ş. tarafından Türkiye Enerji Piyasalarına dair çeşitli birçok verinin paylaşılmakta olduğu Şeffaflık Platfomuna dair çalışmalar
